# Generated by Django 5.0.6 on 2024-06-06 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='image',
        ),
        migrations.AlterField(
            model_name='farm',
            name='contact',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='FarmImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='farm_images/')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='farmhouse.farm')),
            ],
        ),
    ]
