# Generated by Django 5.0.6 on 2024-06-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
