# Generated by Django 5.0.6 on 2024-06-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0004_booking_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
